### ISSUE TITLE
Can't start.

### ISSUE THREAD

**Issue by oxidrake** [ChrisMiuchiz/Cube-World-Mod-Launcher#2]
![image](https://user-images.githubusercontent.com/40744352/49704379-46ff6e00-fc23-11e8-8107-c630e53b5065.png)
![image](https://user-images.githubusercontent.com/40744352/49704384-4e267c00-fc23-11e8-881c-fad808ff470d.png)
Starting launcher, all closes and then nothing happens.

**Comment by ChrisMiuchiz** [comment]
The first screenshot does not seem to be related because it shows a tool other than the mod launcher in the foreground.

Does the game successfully launch when you remove the mods?
