### ISSUE TITLE
CallbackManager/main.cpp imports a header file "main.h" that isn't in the repo

### ISSUE THREAD

**Issue by calebccff** [ChrisMiuchiz/Cube-World-Mod-Launcher#3]
I'm really interesting in using this code to try and learn modding, especially for CubeWorld. Apologies if this is an obvious mistake, would love to be able to compile this project.

**Comment by CeejayZSmith** [comment]
I am also in the same position. If you switch the branch to 1.0.0-0 there is a main.h that is possibly similar enough to recreate it locally, but having the actual one would be better.

**Comment by CeejayZSmith** [comment]
Looks like it was added in [794ab73](https://github.com/ChrisMiuchiz/Cube-World-Mod-Launcher/commit/794ab735b4da39de598e1b29b2757fd50a4e3f5a) if you are still interested.

**Comment by ChrisMiuchiz** [comment]
This was addressed in the legacy branch and is no longer an issue in the master branch for the release of Cube World.
