### ISSUE TITLE
How to open .dat files?

### ISSUE THREAD

**Issue by Kakaaakak** [ChrisMiuchiz/Cube-World-Mod-Launcher#4]
I know that maybe my issue isn't about this launcher, but whatever.
I'm trying to modify CW but there's an issue and I'm asking for help. I don't know how to open .dat files. I tried some unpackers but they didn't do a thing. I saw your mods (they're so good) and I know that you are working with .dll files but maybe you know how to deal with my problem. Whatsoever, thank you.

**Comment by ChrisMiuchiz** [comment]
Cube World's files with the extension .dat are TTF files.
